/**
 * @file update-ip.js
 * @description Tự động phát hiện địa chỉ IPv4 Wi-Fi/LAN của máy tính và cập nhật vào doan-kltn-mobile/.env.
 * Giúp thiết bị thật (iOS/Android qua Expo Go) luôn kết nối chính xác tới NestJS Backend.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

function getLocalIpAddress() {
  const interfaces = os.networkInterfaces();
  const priorityNames = ['wi-fi', 'wifi', 'ethernet', 'wlan', 'en0', 'eth0', 'wireless'];
  const ignoredPatterns = [
    'vethernet',
    'wsl',
    'virtualbox',
    'vmware',
    'loopback',
    'hyper-v',
    'docker',
    'tailscale',
    'pseudo',
    'tap',
    'tun',
    'teredo',
    'bluetooth',
  ];

  let candidateIps = [];

  for (const [name, netList] of Object.entries(interfaces)) {
    const lowerName = name.toLowerCase();
    const isIgnored = ignoredPatterns.some((pattern) => lowerName.includes(pattern));
    if (isIgnored) continue;

    for (const net of netList) {
      if (net.family === 'IPv4' && !net.internal) {
        const isPriority = priorityNames.some((p) => lowerName.includes(p));
        candidateIps.push({
          name,
          ip: net.address,
          isPriority,
        });
      }
    }
  }

  // 1. Ưu tiên card Wi-Fi / Ethernet
  const priorityMatch = candidateIps.find((c) => c.isPriority);
  if (priorityMatch) {
    return { ip: priorityMatch.ip, interfaceName: priorityMatch.name };
  }

  // 2. Lấy candidate đầu tiên không phải internal
  if (candidateIps.length > 0) {
    return { ip: candidateIps[0].ip, interfaceName: candidateIps[0].name };
  }

  return { ip: '127.0.0.1', interfaceName: 'localhost' };
}

function updateMobileEnv() {
  const { ip, interfaceName } = getLocalIpAddress();
  const envPath = path.resolve(__dirname, '..', 'doan-kltn-mobile', '.env');

  const envContent = [
    `# ================================================================`,
    `# AUTO-GENERATED BY scripts/update-ip.js (${new Date().toLocaleString('vi-VN')})`,
    `# Card mạng đang kết nối: ${interfaceName} (${ip})`,
    `# ================================================================`,
    `EXPO_PUBLIC_API_URL=http://${ip}:3000/api`,
    `EXPO_PUBLIC_SOCKET_URL=http://${ip}:3000`,
    `EXPO_PUBLIC_ENV=development`,
    ``,
  ].join('\n');

  fs.writeFileSync(envPath, envContent, 'utf-8');

  console.log(`📡 [Network Sync] Phát hiện IPv4 nội bộ: ${ip} (Interface: ${interfaceName})`);
  console.log(`✅ [Network Sync] Đã cập nhật doan-kltn-mobile/.env:`);
  console.log(`   - EXPO_PUBLIC_API_URL:    http://${ip}:3000/api`);
  console.log(`   - EXPO_PUBLIC_SOCKET_URL: http://${ip}:3000`);
}

updateMobileEnv();
